modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="decimation_core"
version="1.0.0"
displayName="Decimation Core"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="sockm, MCreator"

[[dependencies.decimation_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




